from __future__ import annotations

import uuid
from typing import Any

from fastembed import SparseTextEmbedding
from qdrant_client import AsyncQdrantClient
from qdrant_client.models import NamedSparseVector, SparseVector

from app.retrieval.filters import RetrievedChunk, build_qdrant_filter
from app.storage.qdrant.collections import SPARSE_VECTOR_NAME, collection_name

_sparse_model: SparseTextEmbedding | None = None


def _get_sparse_model() -> SparseTextEmbedding:
    global _sparse_model
    if _sparse_model is None:
        _sparse_model = SparseTextEmbedding(model_name="prithivida/Splade_PP_en_v1")
    return _sparse_model


class SparseRetriever:
    """
    Lexical/sparse retrieval using Qdrant's built-in sparse vector support
    with SPLADE embeddings generated by fastembed.
    """

    def __init__(self, client: AsyncQdrantClient) -> None:
        self._client = client

    async def retrieve(
        self,
        query: str,
        knowledge_base_id: uuid.UUID,
        top_k: int = 20,
        filters: dict[str, Any] | None = None,
    ) -> list[RetrievedChunk]:
        coll = collection_name(knowledge_base_id)

        model = _get_sparse_model()
        results_gen = model.embed([query])
        embedding = list(results_gen)[0]
        sparse_vec = SparseVector(
            indices=embedding.indices.tolist(),
            values=embedding.values.tolist(),
        )

        qdrant_filter = None
        if filters:
            qdrant_filter = build_qdrant_filter(filters)

        hits = await self._client.search(
            collection_name=coll,
            query_vector=NamedSparseVector(name=SPARSE_VECTOR_NAME, vector=sparse_vec),
            limit=top_k,
            query_filter=qdrant_filter,
            with_payload=True,
        )

        chunks: list[RetrievedChunk] = []
        for hit in hits:
            payload = hit.payload or {}
            chunks.append(
                RetrievedChunk(
                    point_id=str(hit.id),
                    text=payload.get("text", ""),
                    score=hit.score,
                    document_id=payload.get("document_id", ""),
                    knowledge_base_id=payload.get("knowledge_base_id", ""),
                    chunk_index=payload.get("chunk_index", 0),
                    title=payload.get("title", ""),
                    source_url=payload.get("source_url"),
                    category=payload.get("category"),
                    document_type=payload.get("document_type"),
                    extra_payload={},
                )
            )
        return chunks
